### ISSUE TITLE
error when install because pandas upgraded

### ISSUE THREAD

**Issue by gorf** [gorf/tushare-trader#1]
>python setup.py install
C:\Users\DELL\Desktop\tushare-trader-master\tushare-trader-master\tushare_trader\stock\classifying.py:16: FutureWarning: pandas.util.testing is deprecated. Use the functions in the public API at pandas.testing instead.
  from pandas.util.testing import _network_error_classes
Traceback (most recent call last):
  File "setup.py", line 4, in <module>
    import tushare_trader
  File "C:\Users\DELL\Desktop\tushare-trader-master\tushare-trader-master\tushare_trader\__init__.py", line 36, in <module>
    from tushare_trader.stock.classifying import (get_industry_classified, get_concept_classified,
  File "C:\Users\DELL\Desktop\tushare-trader-master~20200412-073515\tushare-trader-master\tushare_trader\stock\classifying.py", line 16, in <module>
    from pandas.util.testing import _network_error_classes
ImportError: cannot import name '_network_error_classes' from 'pandas.util.testing' (C:\Users\DELL\AppData\Local\Programs\Python\Python37\lib\site-packages\pandas\util\testing.py)

>pip list
Package          Version
---------------- ----------
backcall         0.2.0
beautifulsoup4   4.9.1
bs4              0.0.1
certifi          2020.4.5.2
chardet          3.0.4
click            7.1.2
colorama         0.4.3
cssselect        1.1.0
decorator        4.4.2
easyquotation    0.7.4
easyutils        0.1.7
et-xmlfile       1.0.1
idna             2.9
ipython          7.15.0
ipython-genutils 0.2.0
jdcal            1.4.1
jedi             0.17.1
Jinja2           2.11.2
lxml             4.5.1
MarkupSafe       1.1.1
numpy            1.18.5
openpyxl         3.0.3
pandas           1.0.4
parso            0.7.0
pickleshare      0.7.5
piecash          1.0.0
Pillow           7.1.2
pip              20.1.1
prompt-toolkit   3.0.5
pygame           1.9.6
Pygments         2.6.1
PyPDF4           1.27.0
pyquery          1.4.1
python-dateutil  2.8.1
pytz             2020.1
pywin32          228
requests         2.23.0
setuptools       40.8.0
simplejson       3.17.0
six              1.15.0
soupsieve        2.0.1
SQLAlchemy       1.3.18
SQLAlchemy-Utils 0.36.6
traitlets        4.3.3
tushare          1.2.60
tzlocal          2.1
urllib3          1.25.9
wcwidth          0.2.5
websocket-client 0.57.0
xlrd             1.2.0

**Comment by gorf** [comment]
solved
